### ISSUE TITLE
Support for scalastyle v1.0.0

### ISSUE THREAD

**Issue by maximskripnik** [codacy/codacy-scalastyle#14]
Can you please update this to support latest version of scalastyle? Some rules were updated there, such as http://www.scalastyle.org/rules-1.0.0.html#org_scalastyle_scalariform_FieldNamesChecker and we can not deal with false negatives, which is irritating.

Thanks in advance

**Comment by pm-Egor-Genning** [comment]
+

**Comment by rtfpessoa** [comment]
We have been collecting more information and should be able to start working in more updates weekly starting in 23 of April.

Will let you know when I have more details.
