### ISSUE TITLE
Structural typing pattern is wrong in Codacy.

### ISSUE THREAD

**Issue by alexflav23** [codacy/codacy-scalastyle#6]
Hi,

First of all apologies if this is the wrong place to report the issue.

```scala
override def request(
  ct: ConcreteOperaTable,
  t: Opera
)(
  implicit session: Session,
  keySpace: KeySpace
): ExecutableStatement with Batchable {...}
```

The automated code review tool is picking patterns such as `def x: Type with AnotherType` as structural, which is false. Those are not structural types in Scala, and the example found in the suggestion only illustrates that particular point further.

As an example, this is directly copy pasted from Twitter's effective Scala.

> Why is this an issue?
> Do not use structural types in normal use. They are a convenient and powerful feature, but > unfortunately do not have an efficient implementation on the JVM. However — due to an implementation > quirk — they provide a very nice shorthand for doing reflection.

```scala
val obj: AnyRef
obj.asInstanceOf[{def close()}].close()
For more details:
Effective Scala
```

> Related code pattern
> Avoid usage of Structural Types
> Do not use structural types in normal use.

**Comment by machadoit** [comment]
Hi @alexflav23,

Thank you for your report, we created an internal ticket to review and fix this pattern, for now just disable the pattern, I will give you updates when it's fix :)

**Comment by pedrorijo91** [comment]
@johannegger maybe this could be (or already has been) solved using our [scalameta](https://github.com/codacy/codacy-scalameta) ?

**Comment by johannegger** [comment]
hi @alexflav23 !

this issue should be fixed, please let me know if it continues showing up.
Thanks for reporting!
