### ISSUE TITLE
Innacurate report against get method.

### ISSUE THREAD

**Issue by alexflav23** [codacy/codacy-scalastyle#7]
The Scala analyser is trying to fight again method calls to `Option.get` as well as prefixing methods with `get$Name`, effectively preventing java-esque accessors like `getUser`, `getName` etc. But the current checker introduces a subtle bug.

There are valid usages of `get` against certain objects who neither prefix nor have anything to do with the `Option` type. One neat trick you could employ is:

- If the method call is on `get` but there are no parens used, this could be an `Option`. Because `Option` defines `get` as `def get: T` with no parantheses, calling `get()` with parentheses on an `Option` will not compile. 

- If the method call is on `get` but there *are* parentheses used, you should not be flagging this at all. If the method name is just `def get()` this doesn't void any known Scala style rules.

- If the method name simply *includes* get, like `getName` or `getUser`, flag it as useless prefixing, according to the Twitter Scala style guidelines which you are currently citing. Right now, the middle case can easily fall in either case 1 or case 3 because the checker does not look at the rest of the signature of a `get` method defined, instead it simply checks if the name *includes* get, instead of checking the full name of the method, checking what params are provided, etc.

**Comment by machadoit** [comment]
Hi @alexflav23,

Once again, thank you for your report, we created a ticket to review it. Actually both issues you reported are not related to this repo, they are implemented on our homemade patterns (which are not yet open-source).

Please keep giving us your feedback, but you can use the support in our website instead :)

Thank you

**Comment by pedrorijo91** [comment]
@johannegger maybe this could be (or already has been) solved using our [scalameta](https://github.com/codacy/codacy-scalameta) ?

**Comment by pedrorijo91** [comment]
Solving in https://github.com/codacy/codacy-scalameta/issues/12
